all: build


run:
	java MainB

clean:
	del expressions\*.class
	del parser\*.class
	del proof\*.class
	del utils\*.class
	del *.class

build:
	javac expressions/*.java
	javac parser/*.java
	javac proof/*.java
	javac utils/*.java
	javac *.java

